# Generated by Django 5.0 on 2023-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_callinfo_organisation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='yandex_disk_link',
            field=models.TextField(),
        ),
    ]
