# Generated by Django 5.0 on 2023-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_callinfo_yandex_disk_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callinfo',
            name='yandex_disk_link',
        ),
        migrations.AddField(
            model_name='callinfo',
            name='call_id',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
    ]
