# Generated by Django 5.0 on 2024-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigProjectsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skorozvon_scenario_name', models.CharField(max_length=255)),
                ('bitrix_project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_field_id', models.IntegerField()),
                ('bitrix_field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('stage_id', models.CharField(max_length=255)),
                ('tg_bot_id', models.CharField(max_length=255)),
                ('google_spreadsheet_id', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('previous_sheet_names', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
