# Generated by Django 5.0 on 2024-01-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_fieldids_bitrix_field_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigProjectsName',
            new_name='ConfigProjectNames',
        ),
    ]
