# Generated by Django 5.0 on 2024-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_alter_calldatainfo_call_connected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(max_length=255)),
                ('scenario_name', models.CharField(max_length=255)),
            ],
        ),
    ]
