# Generated by Django 5.0 on 2024-02-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_formresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
    ]
