# Generated by Django 5.0 on 2024-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_formfieldids'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='form_scenario_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
