# Generated by Django 5.0 on 2024-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_formresponse_form_scenario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='form_scenario_id',
            field=models.IntegerField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scenarioids',
            name='scenario_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
