# Generated by Django 5.0 on 2024-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_formresponse_form_scenario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
    ]
