# Generated by Django 5.0 on 2024-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_alter_formresponse_form_scenario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='form_scenario_id',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='scenarioids',
            name='scenario_id',
            field=models.IntegerField(),
        ),
    ]
